package orm;
// Generated 5 Oct, 2012 10:24:47 AM by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;




/**
 * Documents generated by hbm2java
 */
public class Documents  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private int createdby;
     private Timestamp createdon;
     
     private Set employeeDocuments;

    public Documents() {
        
    }

    public Documents(int id, String name , String description , int createdby , Timestamp createdon ) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.createdby = createdby;
       this.createdon = createdon;
       this.employeeDocuments = new HashSet(0);
    }

    public Set getEmployeeDocuments() {
        return employeeDocuments;
    }

    public void setEmployeeDocuments(Set employeeDocuments) {
        this.employeeDocuments = employeeDocuments;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getCreatedby() {
        return createdby;
    }

    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Timestamp getCreatedon() {
        return createdon;
    }

    public void setCreatedon(Timestamp createdon) {
        this.createdon = createdon;
    }


}


