package orm;
// Generated 27 Sep, 2012 12:53:50 PM by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees implements java.io.Serializable {

    private int id;
    private String firstname;
    private String lastname;
    private Date joiningDate;
    private String tempAddress;
    private String permAddress;
    private char gender;
    private char maritalStatus;
    private String tempPin;
    private String permPin;
    private Date birthDate;
    private String passportNo;
    private Date passportExpdate;
    private String passportCopy;
    private String emerCtc;
    private String emerCtcNo;
    private String emerCtcRel;
    private String phone;
    private String nationality;
    private String tempCity;
    private String tempState;
    private String tempCountry;
    private String permCity;
    private String permState;
    private String permCountry;
    private String photo;
    private Date leavingDate;
    private String leavingReason;
    private int createdby;
    private Timestamp createdon;
    private String employeeno;
    private String email;
    private Set employeeDocuments;
    private Set employeeQualifications;
    private Set employeeResponsibilities;
    private Set employeeDetails;
    private Set employeePropertyIssued;
    private Set employeeDesignations;
    private Set employeeEmploymenttypes;
    private Set users;
    private Set projectIncharge;
    private Set departmentIncharge;
    private Set inwordse;
    private Set todofor;
    private Set requestTo;
    private Set requestFrom;
    private Set icFolders;

    public Employees() {
    }

    public Employees(int id, String firstname, String lastname, Date joiningDate, String tempAddress, String permAddress, char gender, char maritalStatus, String tempPin, String permPin, Date birthDate, String emerCtcNo, String emerCtcRel, String phone, String nationality, String tempCity, String tempState, String tempCountry, String permCity, String permState, String permCountry, String emerCtc, String photo, Date leavingDate, String leavingReason, String employeeno, String email) {
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.joiningDate = joiningDate;
        this.tempAddress = tempAddress;
        this.permAddress = permAddress;
        this.gender = gender;
        this.maritalStatus = maritalStatus;
        this.tempPin = tempPin;
        this.permPin = permPin;
        this.birthDate = birthDate;
        this.emerCtcNo = emerCtcNo;
        this.emerCtcRel = emerCtcRel;
        this.phone = phone;
        this.nationality = nationality;
        this.tempCity = tempCity;
        this.tempState = tempState;
        this.tempCountry = tempCountry;
        this.permCity = permCity;
        this.permState = permState;
        this.permCountry = permCountry;
        this.emerCtc = emerCtc;
        this.photo = photo;
        this.leavingDate = leavingDate;
        this.leavingReason = leavingReason;
        this.employeeno = employeeno;
        this.email = email;

        this.employeeDocuments = new HashSet(0);
        this.employeeQualifications = new HashSet(0);
        this.employeeResponsibilities = new HashSet(0);
        this.employeeDetails = new HashSet(0);
        this.employeePropertyIssued = new HashSet(0);
        this.employeeDesignations = new HashSet(0);
        this.employeeEmploymenttypes = new HashSet(0);
        this.projectIncharge = new HashSet(0);
        this.departmentIncharge = new HashSet(0);
        this.inwordse = new HashSet(0);
        this.todofor = new HashSet(0);
        this.requestTo = new HashSet(0);
        this.requestFrom = new HashSet(0);
        this.icFolders = new HashSet(0);
    }

    public Employees(int id, String firstname, String lastname, Date joiningDate, String tempAddress, String permAddress, char gender, char maritalStatus, String tempPin, String permPin, Date birthDate, String passportNo, Date passportExpdate, String passportCopy, String emerCtcNo, String emerCtcRel, String phone, String nationality, String tempCity, String tempState, String tempCountry, String permCity, String permState, String permCountry, String emerCtc, String photo, Date leavingDate, String leavingReason, int createdby, Timestamp createdon, String employeeno, String email) {
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.joiningDate = joiningDate;
        this.tempAddress = tempAddress;
        this.permAddress = permAddress;
        this.gender = gender;
        this.maritalStatus = maritalStatus;
        this.tempPin = tempPin;
        this.permPin = permPin;
        this.birthDate = birthDate;
        this.passportNo = passportNo;
        this.passportExpdate = passportExpdate;
        this.passportCopy = passportCopy;
        this.emerCtcNo = emerCtcNo;
        this.emerCtcRel = emerCtcRel;
        this.phone = phone;
        this.nationality = nationality;
        this.tempCity = tempCity;
        this.tempState = tempState;
        this.tempCountry = tempCountry;
        this.permCity = permCity;
        this.permState = permState;
        this.permCountry = permCountry;
        this.emerCtc = emerCtc;
        this.photo = photo;
        this.leavingDate = leavingDate;
        this.leavingReason = leavingReason;
        this.createdby = createdby;
        this.createdon = createdon;
        this.employeeno = employeeno;
        this.email = email;

        this.employeeDocuments = new HashSet(0);
        this.employeeQualifications = new HashSet(0);
        this.employeeResponsibilities = new HashSet(0);
        this.employeeDetails = new HashSet(0);
        this.employeePropertyIssued = new HashSet(0);
        this.employeeDesignations = new HashSet(0);
        this.employeeEmploymenttypes = new HashSet(0);
        this.users = new HashSet(0);
        this.projectIncharge = new HashSet(0);
        this.departmentIncharge = new HashSet(0);
        this.inwordse = new HashSet(0);
        this.todofor = new HashSet(0);
        this.requestTo = new HashSet(0);
        this.requestFrom = new HashSet(0);
        this.icFolders = new HashSet(0);
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Date getJoiningDate() {
        return this.joiningDate;
    }

    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    public String getTempAddress() {
        return this.tempAddress;
    }

    public void setTempAddress(String tempAddress) {
        this.tempAddress = tempAddress;
    }

    public String getPermAddress() {
        return this.permAddress;
    }

    public void setPermAddress(String permAddress) {
        this.permAddress = permAddress;
    }

    public char getGender() {
        return this.gender;
    }

    public void setGender(char gender) {
        this.gender = gender;
    }

    public char getMaritalStatus() {
        return this.maritalStatus;
    }

    public void setMaritalStatus(char maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    public String getTempPin() {
        return this.tempPin;
    }

    public void setTempPin(String tempPin) {
        this.tempPin = tempPin;
    }

    public String getPermPin() {
        return this.permPin;
    }

    public void setPermPin(String permPin) {
        this.permPin = permPin;
    }

    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getPassportNo() {
        return this.passportNo;
    }

    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    public Date getPassportExpdate() {
        return this.passportExpdate;
    }

    public void setPassportExpdate(Date passportExpdate) {
        this.passportExpdate = passportExpdate;
    }

    public String getPassportCopy() {
        return this.passportCopy;
    }

    public void setPassportCopy(String passportCopy) {
        this.passportCopy = passportCopy;
    }

    public String getEmerCtcNo() {
        return this.emerCtcNo;
    }

    public void setEmerCtcNo(String emerCtcNo) {
        this.emerCtcNo = emerCtcNo;
    }

    public String getEmerCtcRel() {
        return this.emerCtcRel;
    }

    public void setEmerCtcRel(String emerCtcRel) {
        this.emerCtcRel = emerCtcRel;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getTempCity() {
        return this.tempCity;
    }

    public void setTempCity(String tempCity) {
        this.tempCity = tempCity;
    }

    public String getTempState() {
        return this.tempState;
    }

    public void setTempState(String tempState) {
        this.tempState = tempState;
    }

    public String getTempCountry() {
        return this.tempCountry;
    }

    public void setTempCountry(String tempCountry) {
        this.tempCountry = tempCountry;
    }

    public String getPermCity() {
        return this.permCity;
    }

    public void setPermCity(String permCity) {
        this.permCity = permCity;
    }

    public String getPermState() {
        return this.permState;
    }

    public void setPermState(String permState) {
        this.permState = permState;
    }

    public String getPermCountry() {
        return this.permCountry;
    }

    public void setPermCountry(String permCountry) {
        this.permCountry = permCountry;
    }

    public String getEmerCtc() {
        return emerCtc;
    }

    public void setEmerCtc(String emerCtc) {
        this.emerCtc = emerCtc;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Set getEmployeeDocuments() {
        return employeeDocuments;
    }

    public void setEmployeeDocuments(Set employeeDocuments) {
        this.employeeDocuments = employeeDocuments;
    }

    public Set getEmployeeQualifications() {
        return employeeQualifications;
    }

    public void setEmployeeQualifications(Set employeeQualifications) {
        this.employeeQualifications = employeeQualifications;
    }

    public Set getEmployeeResponsibilities() {
        return employeeResponsibilities;
    }

    public void setEmployeeResponsibilities(Set employeeResponsibilities) {
        this.employeeResponsibilities = employeeResponsibilities;
    }

    public Date getLeavingDate() {
        return leavingDate;
    }

    public void setLeavingDate(Date leavingDate) {
        this.leavingDate = leavingDate;
    }

    public String getLeavingReason() {
        return leavingReason;
    }

    public void setLeavingReason(String leavingReason) {
        this.leavingReason = leavingReason;
    }

    public Set getEmployeeDetails() {
        return employeeDetails;
    }

    public void setEmployeeDetails(Set employeeDetails) {
        this.employeeDetails = employeeDetails;
    }

    public Set getEmployeePropertyIssued() {
        return employeePropertyIssued;
    }

    public void setEmployeePropertyIssued(Set employeePropertyIssued) {
        this.employeePropertyIssued = employeePropertyIssued;
    }

    public int getCreatedby() {
        return createdby;
    }

    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Timestamp getCreatedon() {
        return createdon;
    }

    public void setCreatedon(Timestamp createdon) {
        this.createdon = createdon;
    }

    public Set getEmployeeDesignations() {
        return employeeDesignations;
    }

    public void setEmployeeDesignations(Set employeeDesignations) {
        this.employeeDesignations = employeeDesignations;
    }

    public Set getEmployeeEmploymenttypes() {
        return employeeEmploymenttypes;
    }

    public void setEmployeeEmploymenttypes(Set employeeEmploymenttypes) {
        this.employeeEmploymenttypes = employeeEmploymenttypes;
    }

    public String getEmployeeno() {
        return employeeno;
    }

    public void setEmployeeno(String employeeno) {
        this.employeeno = employeeno;
    }

    public Set getUsers() {
        return users;
    }

    public void setUsers(Set users) {
        this.users = users;
    }

    public Set getProjectIncharge() {
        return projectIncharge;
    }

    public void setProjectIncharge(Set projectIncharge) {
        this.projectIncharge = projectIncharge;
    }

    public Set getDepartmentIncharge() {
        return departmentIncharge;
    }

    public void setDepartmentIncharge(Set departmentIncharge) {
        this.departmentIncharge = departmentIncharge;
    }

    public Set getInwordse() {
        return inwordse;
    }

    public void setInwordse(Set inwordse) {
        this.inwordse = inwordse;
    }

    public Set getTodofor() {
        return todofor;
    }

    public void setTodofor(Set todofor) {
        this.todofor = todofor;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set getRequestTo() {
        return requestTo;
    }

    public void setRequestTo(Set requestTo) {
        this.requestTo = requestTo;
    }

    public Set getRequestFrom() {
        return requestFrom;
    }

    public void setRequestFrom(Set requestFrom) {
        this.requestFrom = requestFrom;
    }

    public Set getIcFolders() {
        return icFolders;
    }

    public void setIcFolders(Set icFolders) {
        this.icFolders = icFolders;
    }
}
