package orm;
// Generated 5 Oct, 2012 10:24:47 AM by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;
import java.util.Date;

/**
 * EmployeeDocuments generated by hbm2java
 */
public class EmployeeDocuments  implements java.io.Serializable {


     private int id;
     private Date expairyDate;
     private Documents documents;
     private Employees employees;
     private String filename;
      private int createdby;
     private Timestamp createdon;

    public EmployeeDocuments() {
    }

    public EmployeeDocuments(int id, Date expairyDate, Documents documents, Employees employees, String filename , int createdby, Timestamp createdon) {
       this.id = id;
       this.expairyDate = expairyDate;
       this.documents = documents;
       this.employees = employees;
       this.filename = filename;
       this.createdby = createdby;
       this.createdon = createdon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getExpairyDate() {
        return this.expairyDate;
    }
    
    public void setExpairyDate(Date expairyDate) {
        this.expairyDate = expairyDate;
    }

    public Documents getDocuments() {
        return documents;
    }

    public void setDocuments(Documents documents) {
        this.documents = documents;
    }

    public Employees getEmployees() {
        return employees;
    }

    public void setEmployees(Employees employees) {
        this.employees = employees;
    }   
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    public int getCreatedby() {
        return createdby;
    }

    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Timestamp getCreatedon() {
        return createdon;
    }

    public void setCreatedon(Timestamp createdon) {
        this.createdon = createdon;
    }


}


