package orm;
// Generated 5 Oct, 2012 10:24:47 AM by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;
import java.util.Date;
import orm.Employees;

/**
 * EmployeeResponsibilities generated by hbm2java
 */
public class EmployeeResponsibilities  implements java.io.Serializable {


     private int id;
     private Responsibilities responsibilities;
     private Employees employees;
     private Date startDate;
     private Date endDate;
     private String endReason;
     private int createdby;
     private Timestamp createdon;

    public EmployeeResponsibilities() {
    }

	
    public EmployeeResponsibilities(int id, Responsibilities responsibilities, Employees employees, Date startDate) {
        this.id = id;
        this.responsibilities = responsibilities;
        this.employees = employees;
        this.startDate = startDate;
    }
    public EmployeeResponsibilities(int id, Responsibilities responsibilities, Employees employees, Date startDate, Date endDate, String endReason, int createdby , Timestamp createdon) {
       this.id = id;
       this.responsibilities = responsibilities;
       this.employees = employees;
       this.startDate = startDate;
       this.endDate = endDate;
       this.endReason = endReason;
       this.createdby = createdby;
       this.createdon = createdon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public Employees getEmployees() {
        return employees;
    }

    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    public Responsibilities getResponsibilities() {
        return responsibilities;
    }

    public void setResponsibilities(Responsibilities responsibilities) {
        this.responsibilities = responsibilities;
    }  
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getEndReason() {
        return this.endReason;
    }
    
    public void setEndReason(String endReason) {
        this.endReason = endReason;
    }

    public int getCreatedby() {
        return createdby;
    }

    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Timestamp getCreatedon() {
        return createdon;
    }

    public void setCreatedon(Timestamp createdon) {
        this.createdon = createdon;
    }

}


