package orm;
// Generated 5 Oct, 2012 10:24:47 AM by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;




/**
 * Responsibilities generated by hbm2java
 */
public class Responsibilities  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private int createdby;
     private Timestamp createdon;
     
     private Set employeeResposibilities;
     private Set designationResponsibilities;

    public Responsibilities() {
    }

    public Responsibilities(int id, String name, String description , int createdby , Timestamp createdon) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.createdby = createdby;
       this.createdon = createdon;
       
       this.employeeResposibilities = new HashSet(0);
       this.designationResponsibilities = new HashSet(0);
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getEmployeeResposibilities() {
        return employeeResposibilities;
    }

    public void setEmployeeResposibilities(Set employeeResposibilities) {
        this.employeeResposibilities = employeeResposibilities;
    }

    public Set getDesignationResponsibilities() {
        return designationResponsibilities;
    }

    public void setDesignationResponsibilities(Set designationResponsibilities) {
        this.designationResponsibilities = designationResponsibilities;
    }

    public int getCreatedby() {
        return createdby;
    }

    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Timestamp getCreatedon() {
        return createdon;
    }

    public void setCreatedon(Timestamp createdon) {
        this.createdon = createdon;
    }
    
}


