package orm;
// Generated 5 Oct, 2012 10:24:47 AM by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private int id;
    private String username;
    private String password;
    private Employees employees;
    private int createdby;
    private Timestamp createdon;
    private Timestamp passwordchangedon;
    private String salt;

    public Users() {
    }

    public Users(int id, String username, String password, Employees employees, int createdby, Timestamp createdon, Timestamp passwordchangedon, String salt) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.employees = employees;
        this.createdby = createdby;
        this.createdon = createdon;
        this.passwordchangedon = passwordchangedon;
        this.salt = salt;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Employees getEmployees() {
        return employees;
    }

    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    public int getCreatedby() {
        return createdby;
    }

    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    public Timestamp getCreatedon() {
        return createdon;
    }

    public void setCreatedon(Timestamp createdon) {
        this.createdon = createdon;
    }

    public Timestamp getPasswordchangedon() {
        return passwordchangedon;
    }

    public void setPasswordchangedon(Timestamp passwordchangedon) {
        this.passwordchangedon = passwordchangedon;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }
}
