package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZDepartments generated by hbm2java
 */
public class ZDepartments  implements java.io.Serializable {


     private int id;
     private int departmentid;
     private String name;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZDepartments() {
    }

	
    public ZDepartments(int id, int departmentid, char opcode, Date modifiedon) {
        this.id = id;
        this.departmentid = departmentid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZDepartments(int id, int departmentid, String name, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.departmentid = departmentid;
       this.name = name;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getDepartmentid() {
        return this.departmentid;
    }
    
    public void setDepartmentid(int departmentid) {
        this.departmentid = departmentid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


