package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZDesignationResponsibilities generated by hbm2java
 */
public class ZDesignationResponsibilities  implements java.io.Serializable {


     private int id;
     private int designationresponsibilityid;
     private Integer responsibilityid;
     private Integer designationid;
     private Date startDate;
     private Date endDate;
     private String endReason;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZDesignationResponsibilities() {
    }

	
    public ZDesignationResponsibilities(int id, int designationresponsibilityid, char opcode, Date modifiedon) {
        this.id = id;
        this.designationresponsibilityid = designationresponsibilityid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZDesignationResponsibilities(int id, int designationresponsibilityid, Integer responsibilityid, Integer designationid, Date startDate, Date endDate, String endReason, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.designationresponsibilityid = designationresponsibilityid;
       this.responsibilityid = responsibilityid;
       this.designationid = designationid;
       this.startDate = startDate;
       this.endDate = endDate;
       this.endReason = endReason;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getDesignationresponsibilityid() {
        return this.designationresponsibilityid;
    }
    
    public void setDesignationresponsibilityid(int designationresponsibilityid) {
        this.designationresponsibilityid = designationresponsibilityid;
    }
    public Integer getResponsibilityid() {
        return this.responsibilityid;
    }
    
    public void setResponsibilityid(Integer responsibilityid) {
        this.responsibilityid = responsibilityid;
    }
    public Integer getDesignationid() {
        return this.designationid;
    }
    
    public void setDesignationid(Integer designationid) {
        this.designationid = designationid;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getEndReason() {
        return this.endReason;
    }
    
    public void setEndReason(String endReason) {
        this.endReason = endReason;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


