package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZDesignations generated by hbm2java
 */
public class ZDesignations  implements java.io.Serializable {


     private int id;
     private int designationid;
     private String name;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZDesignations() {
    }

	
    public ZDesignations(int id, int designationid, char opcode, Date modifiedon) {
        this.id = id;
        this.designationid = designationid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZDesignations(int id, int designationid, String name, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.designationid = designationid;
       this.name = name;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getDesignationid() {
        return this.designationid;
    }
    
    public void setDesignationid(int designationid) {
        this.designationid = designationid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


