package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZDocuments generated by hbm2java
 */
public class ZDocuments  implements java.io.Serializable {


     private int id;
     private int documentid;
     private String name;
     private String description;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZDocuments() {
    }

	
    public ZDocuments(int id, int documentid, char opcode, Date modifiedon) {
        this.id = id;
        this.documentid = documentid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZDocuments(int id, int documentid, String name, String description, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.documentid = documentid;
       this.name = name;
       this.description = description;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getDocumentid() {
        return this.documentid;
    }
    
    public void setDocumentid(int documentid) {
        this.documentid = documentid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


