package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZEmployeeQualifications generated by hbm2java
 */
public class ZEmployeeQualifications  implements java.io.Serializable {


     private int id;
     private Integer qualificationid;
     private int employeeid;
     private String filename;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZEmployeeQualifications() {
    }

	
    public ZEmployeeQualifications(int id, int employeeid, char opcode, Date modifiedon) {
        this.id = id;
        this.employeeid = employeeid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZEmployeeQualifications(int id, Integer qualificationid, int employeeid, String filename, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.qualificationid = qualificationid;
       this.employeeid = employeeid;
       this.filename = filename;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getQualificationid() {
        return this.qualificationid;
    }
    
    public void setQualificationid(Integer qualificationid) {
        this.qualificationid = qualificationid;
    }
    public int getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(int employeeid) {
        this.employeeid = employeeid;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


