package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * ZEmployees generated by hbm2java
 */
public class ZEmployees implements java.io.Serializable {

    private int id;
    private int employeeId;
    private String firstname;
    private String lastname;
    private Date joiningDate;
    private String tempAddress;
    private String permAddress;
    private Character gender;
    private Character maritalStatus;
    private String tempPin;
    private String permPin;
    private Date birthDate;
    private String passportNo;
    private Date passportExpdate;
    private String passportCopy;
    private String emerCtcNo;
    private String emerCtcRel;
    private String phone;
    private String nationality;
    private String tempCity;
    private String tempState;
    private String tempCountry;
    private String permCity;
    private String permState;
    private String permCountry;
    private String emerCtc;
    private String photo;
    private Date leavingdate;
    private String leavingreason;
    private char opcode;
    private Integer modifiedby;
    private Date modifiedon;
    private String employeeno;
    private String email;

    public ZEmployees() {
    }

    public ZEmployees(int id, int employeeId, char opcode, Date modifiedon) {
        this.id = id;
        this.employeeId = employeeId;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }

    public ZEmployees(int id, int employeeId, String firstname, String lastname, Date joiningDate, String tempAddress, String permAddress, Character gender, Character maritalStatus, String tempPin, String permPin, Date birthDate, String passportNo, Date passportExpdate, String passportCopy, String emerCtcNo, String emerCtcRel, String phone, String nationality, String tempCity, String tempState, String tempCountry, String permCity, String permState, String permCountry, String emerCtc, String photo, Date leavingdate, String leavingreason, char opcode, Integer modifiedby, Date modifiedon, String employeeno, String email) {
        this.id = id;
        this.employeeId = employeeId;
        this.firstname = firstname;
        this.lastname = lastname;
        this.joiningDate = joiningDate;
        this.tempAddress = tempAddress;
        this.permAddress = permAddress;
        this.gender = gender;
        this.maritalStatus = maritalStatus;
        this.tempPin = tempPin;
        this.permPin = permPin;
        this.birthDate = birthDate;
        this.passportNo = passportNo;
        this.passportExpdate = passportExpdate;
        this.passportCopy = passportCopy;
        this.emerCtcNo = emerCtcNo;
        this.emerCtcRel = emerCtcRel;
        this.phone = phone;
        this.nationality = nationality;
        this.tempCity = tempCity;
        this.tempState = tempState;
        this.tempCountry = tempCountry;
        this.permCity = permCity;
        this.permState = permState;
        this.permCountry = permCountry;
        this.emerCtc = emerCtc;
        this.photo = photo;
        this.leavingdate = leavingdate;
        this.leavingreason = leavingreason;
        this.opcode = opcode;
        this.modifiedby = modifiedby;
        this.modifiedon = modifiedon;
        this.employeeno = employeeno;
        this.email = email;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Date getJoiningDate() {
        return this.joiningDate;
    }

    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    public String getTempAddress() {
        return this.tempAddress;
    }

    public void setTempAddress(String tempAddress) {
        this.tempAddress = tempAddress;
    }

    public String getPermAddress() {
        return this.permAddress;
    }

    public void setPermAddress(String permAddress) {
        this.permAddress = permAddress;
    }

    public Character getGender() {
        return this.gender;
    }

    public void setGender(Character gender) {
        this.gender = gender;
    }

    public Character getMaritalStatus() {
        return this.maritalStatus;
    }

    public void setMaritalStatus(Character maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    public String getTempPin() {
        return this.tempPin;
    }

    public void setTempPin(String tempPin) {
        this.tempPin = tempPin;
    }

    public String getPermPin() {
        return this.permPin;
    }

    public void setPermPin(String permPin) {
        this.permPin = permPin;
    }

    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getPassportNo() {
        return this.passportNo;
    }

    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    public Date getPassportExpdate() {
        return this.passportExpdate;
    }

    public void setPassportExpdate(Date passportExpdate) {
        this.passportExpdate = passportExpdate;
    }

    public String getPassportCopy() {
        return this.passportCopy;
    }

    public void setPassportCopy(String passportCopy) {
        this.passportCopy = passportCopy;
    }

    public String getEmerCtcNo() {
        return this.emerCtcNo;
    }

    public void setEmerCtcNo(String emerCtcNo) {
        this.emerCtcNo = emerCtcNo;
    }

    public String getEmerCtcRel() {
        return this.emerCtcRel;
    }

    public void setEmerCtcRel(String emerCtcRel) {
        this.emerCtcRel = emerCtcRel;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getTempCity() {
        return this.tempCity;
    }

    public void setTempCity(String tempCity) {
        this.tempCity = tempCity;
    }

    public String getTempState() {
        return this.tempState;
    }

    public void setTempState(String tempState) {
        this.tempState = tempState;
    }

    public String getTempCountry() {
        return this.tempCountry;
    }

    public void setTempCountry(String tempCountry) {
        this.tempCountry = tempCountry;
    }

    public String getPermCity() {
        return this.permCity;
    }

    public void setPermCity(String permCity) {
        this.permCity = permCity;
    }

    public String getPermState() {
        return this.permState;
    }

    public void setPermState(String permState) {
        this.permState = permState;
    }

    public String getPermCountry() {
        return this.permCountry;
    }

    public void setPermCountry(String permCountry) {
        this.permCountry = permCountry;
    }

    public String getEmerCtc() {
        return this.emerCtc;
    }

    public void setEmerCtc(String emerCtc) {
        this.emerCtc = emerCtc;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Date getLeavingdate() {
        return this.leavingdate;
    }

    public void setLeavingdate(Date leavingdate) {
        this.leavingdate = leavingdate;
    }

    public String getLeavingreason() {
        return this.leavingreason;
    }

    public void setLeavingreason(String leavingreason) {
        this.leavingreason = leavingreason;
    }

    public char getOpcode() {
        return this.opcode;
    }

    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }

    public Integer getModifiedby() {
        return this.modifiedby;
    }

    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }

    public Date getModifiedon() {
        return this.modifiedon;
    }

    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }

    public String getEmployeeno() {
        return employeeno;
    }

    public void setEmployeeno(String employeeno) {
        this.employeeno = employeeno;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
