package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZEmployeeDocuments generated by hbm2java
 */
public class ZEmployeeDocuments  implements java.io.Serializable {


     private int id;
     private int employeedocumentid;
     private Date expairyDate;
     private Integer documentid;
     private int employeeid;
     private String filename;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZEmployeeDocuments() {
    }

	
    public ZEmployeeDocuments(int id, int employeedocumentid, int employeeid, char opcode, Date modifiedon) {
        this.id = id;
        this.employeedocumentid = employeedocumentid;
        this.employeeid = employeeid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZEmployeeDocuments(int id, int employeedocumentid, Date expairyDate, Integer documentid, int employeeid, String filename, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.employeedocumentid = employeedocumentid;
       this.expairyDate = expairyDate;
       this.documentid = documentid;
       this.employeeid = employeeid;
       this.filename = filename;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getEmployeedocumentid() {
        return this.employeedocumentid;
    }
    
    public void setEmployeedocumentid(int employeedocumentid) {
        this.employeedocumentid = employeedocumentid;
    }
    public Date getExpairyDate() {
        return this.expairyDate;
    }
    
    public void setExpairyDate(Date expairyDate) {
        this.expairyDate = expairyDate;
    }
    public Integer getDocumentid() {
        return this.documentid;
    }
    
    public void setDocumentid(Integer documentid) {
        this.documentid = documentid;
    }
    public int getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(int employeeid) {
        this.employeeid = employeeid;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


