package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZEmployeeDetails generated by hbm2java
 */
public class ZEmployeeDetails  implements java.io.Serializable {


     private int id;
     private int employeedetailsid;
     private Integer projectid;
     private Integer locationid;
     private Integer designationid;
     private Integer departmentid;
     private int employeeid;
     private Date startDate;
     private Date endDate;
     private String endReason;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZEmployeeDetails() {
    }

	
    public ZEmployeeDetails(int id, int employeedetailsid, int employeeid, char opcode, Date modifiedon) {
        this.id = id;
        this.employeedetailsid = employeedetailsid;
        this.employeeid = employeeid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZEmployeeDetails(int id, int employeedetailsid, Integer projectid, Integer locationid, Integer designationid, Integer departmentid, int employeeid, Date startDate, Date endDate, String endReason, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.employeedetailsid = employeedetailsid;
       this.projectid = projectid;
       this.locationid = locationid;
       this.designationid = designationid;
       this.departmentid = departmentid;
       this.employeeid = employeeid;
       this.startDate = startDate;
       this.endDate = endDate;
       this.endReason = endReason;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getEmployeedetailsid() {
        return this.employeedetailsid;
    }
    
    public void setEmployeedetailsid(int employeedetailsid) {
        this.employeedetailsid = employeedetailsid;
    }
    public Integer getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }
    public Integer getLocationid() {
        return this.locationid;
    }
    
    public void setLocationid(Integer locationid) {
        this.locationid = locationid;
    }
    public Integer getDesignationid() {
        return this.designationid;
    }
    
    public void setDesignationid(Integer designationid) {
        this.designationid = designationid;
    }
    public Integer getDepartmentid() {
        return this.departmentid;
    }
    
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }
    public int getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(int employeeid) {
        this.employeeid = employeeid;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getEndReason() {
        return this.endReason;
    }
    
    public void setEndReason(String endReason) {
        this.endReason = endReason;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


