package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZLocations generated by hbm2java
 */
public class ZLocations  implements java.io.Serializable {


     private int id;
     private int locationid;
     private String name;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZLocations() {
    }

	
    public ZLocations(int id, int locationid, char opcode, Date modifiedon) {
        this.id = id;
        this.locationid = locationid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZLocations(int id, int locationid, String name, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.locationid = locationid;
       this.name = name;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getLocationid() {
        return this.locationid;
    }
    
    public void setLocationid(int locationid) {
        this.locationid = locationid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


