package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZLoginDetails generated by hbm2java
 */
public class ZLoginDetails  implements java.io.Serializable {


     private int id;
     private int logindetailsid;
     private String ipaddress;
     private Date loginDate;
     private Date logoutDate;
     private Character issuccess;
     private String failReason;
     private String username;
     private String sessionid;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZLoginDetails() {
    }

	
    public ZLoginDetails(int id, int logindetailsid, char opcode, Date modifiedon) {
        this.id = id;
        this.logindetailsid = logindetailsid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZLoginDetails(int id, int logindetailsid, String ipaddress, Date loginDate, Date logoutDate, Character issuccess, String failReason, String username, String sessionid, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.logindetailsid = logindetailsid;
       this.ipaddress = ipaddress;
       this.loginDate = loginDate;
       this.logoutDate = logoutDate;
       this.issuccess = issuccess;
       this.failReason = failReason;
       this.username = username;
       this.sessionid = sessionid;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getLogindetailsid() {
        return this.logindetailsid;
    }
    
    public void setLogindetailsid(int logindetailsid) {
        this.logindetailsid = logindetailsid;
    }
    public String getIpaddress() {
        return this.ipaddress;
    }
    
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }
    public Date getLoginDate() {
        return this.loginDate;
    }
    
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }
    public Date getLogoutDate() {
        return this.logoutDate;
    }
    
    public void setLogoutDate(Date logoutDate) {
        this.logoutDate = logoutDate;
    }
    public Character getIssuccess() {
        return this.issuccess;
    }
    
    public void setIssuccess(Character issuccess) {
        this.issuccess = issuccess;
    }
    public String getFailReason() {
        return this.failReason;
    }
    
    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getSessionid() {
        return this.sessionid;
    }
    
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


