package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZPropertyissue generated by hbm2java
 */
public class ZPropertyissue  implements java.io.Serializable {


     private int id;
     private int propertyissueid;
     private int employeeid;
     private Integer propertyid;
     private Integer unitid;
     private String comments;
     private Integer issuedby;
     private Date issuedbyIssuedate;
     private Integer returnedby;
     private Date returnedbyReturndate;
     private Integer verifiedby;
     private Date verifiedbyVerifieddate;
     private String quantity;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZPropertyissue() {
    }

	
    public ZPropertyissue(int id, int propertyissueid, int employeeid, char opcode, Date modifiedon) {
        this.id = id;
        this.propertyissueid = propertyissueid;
        this.employeeid = employeeid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZPropertyissue(int id, int propertyissueid, int employeeid, Integer propertyid, Integer unitid, String comments, Integer issuedby, Date issuedbyIssuedate, Integer returnedby, Date returnedbyReturndate, Integer verifiedby, Date verifiedbyVerifieddate, String quantity, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.propertyissueid = propertyissueid;
       this.employeeid = employeeid;
       this.propertyid = propertyid;
       this.unitid = unitid;
       this.comments = comments;
       this.issuedby = issuedby;
       this.issuedbyIssuedate = issuedbyIssuedate;
       this.returnedby = returnedby;
       this.returnedbyReturndate = returnedbyReturndate;
       this.verifiedby = verifiedby;
       this.verifiedbyVerifieddate = verifiedbyVerifieddate;
       this.quantity = quantity;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPropertyissueid() {
        return this.propertyissueid;
    }
    
    public void setPropertyissueid(int propertyissueid) {
        this.propertyissueid = propertyissueid;
    }
    public int getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(int employeeid) {
        this.employeeid = employeeid;
    }
    public Integer getPropertyid() {
        return this.propertyid;
    }
    
    public void setPropertyid(Integer propertyid) {
        this.propertyid = propertyid;
    }
    public Integer getUnitid() {
        return this.unitid;
    }
    
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Integer getIssuedby() {
        return this.issuedby;
    }
    
    public void setIssuedby(Integer issuedby) {
        this.issuedby = issuedby;
    }
    public Date getIssuedbyIssuedate() {
        return this.issuedbyIssuedate;
    }
    
    public void setIssuedbyIssuedate(Date issuedbyIssuedate) {
        this.issuedbyIssuedate = issuedbyIssuedate;
    }
    public Integer getReturnedby() {
        return this.returnedby;
    }
    
    public void setReturnedby(Integer returnedby) {
        this.returnedby = returnedby;
    }
    public Date getReturnedbyReturndate() {
        return this.returnedbyReturndate;
    }
    
    public void setReturnedbyReturndate(Date returnedbyReturndate) {
        this.returnedbyReturndate = returnedbyReturndate;
    }
    public Integer getVerifiedby() {
        return this.verifiedby;
    }
    
    public void setVerifiedby(Integer verifiedby) {
        this.verifiedby = verifiedby;
    }
    public Date getVerifiedbyVerifieddate() {
        return this.verifiedbyVerifieddate;
    }
    
    public void setVerifiedbyVerifieddate(Date verifiedbyVerifieddate) {
        this.verifiedbyVerifieddate = verifiedbyVerifieddate;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


