package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZProperties generated by hbm2java
 */
public class ZProperties  implements java.io.Serializable {


     private int id;
     private int propertyid;
     private String name;
     private String description;
     private Character PType;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZProperties() {
    }

	
    public ZProperties(int id, int propertyid, char opcode, Date modifiedon) {
        this.id = id;
        this.propertyid = propertyid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZProperties(int id, int propertyid, String name, String description, Character PType, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.propertyid = propertyid;
       this.name = name;
       this.description = description;
       this.PType = PType;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPropertyid() {
        return this.propertyid;
    }
    
    public void setPropertyid(int propertyid) {
        this.propertyid = propertyid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Character getPType() {
        return this.PType;
    }
    
    public void setPType(Character PType) {
        this.PType = PType;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


