package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZUserRoles generated by hbm2java
 */
public class ZUserRoles  implements java.io.Serializable {


     private int id;
     private int userroleid;
     private Integer userid;
     private Integer roleid;
     private Date startDate;
     private Date endDate;
     private String endReason;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZUserRoles() {
    }

	
    public ZUserRoles(int id, int userroleid, char opcode, Date modifiedon) {
        this.id = id;
        this.userroleid = userroleid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZUserRoles(int id, int userroleid, Integer userid, Integer roleid, Date startDate, Date endDate, String endReason, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.userroleid = userroleid;
       this.userid = userid;
       this.roleid = roleid;
       this.startDate = startDate;
       this.endDate = endDate;
       this.endReason = endReason;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUserroleid() {
        return this.userroleid;
    }
    
    public void setUserroleid(int userroleid) {
        this.userroleid = userroleid;
    }
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public Integer getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getEndReason() {
        return this.endReason;
    }
    
    public void setEndReason(String endReason) {
        this.endReason = endReason;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


