package orm;
// Generated 12 Feb, 2013 3:25:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ZUserLocking generated by hbm2java
 */
public class ZUserLocking  implements java.io.Serializable {


     private int id;
     private int userlockingid;
     private Integer userid;
     private Date lockDate;
     private String lockReason;
     private Date unlockDate;
     private char opcode;
     private Integer modifiedby;
     private Date modifiedon;

    public ZUserLocking() {
    }

	
    public ZUserLocking(int id, int userlockingid, char opcode, Date modifiedon) {
        this.id = id;
        this.userlockingid = userlockingid;
        this.opcode = opcode;
        this.modifiedon = modifiedon;
    }
    public ZUserLocking(int id, int userlockingid, Integer userid, Date lockDate, String lockReason, Date unlockDate, char opcode, Integer modifiedby, Date modifiedon) {
       this.id = id;
       this.userlockingid = userlockingid;
       this.userid = userid;
       this.lockDate = lockDate;
       this.lockReason = lockReason;
       this.unlockDate = unlockDate;
       this.opcode = opcode;
       this.modifiedby = modifiedby;
       this.modifiedon = modifiedon;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUserlockingid() {
        return this.userlockingid;
    }
    
    public void setUserlockingid(int userlockingid) {
        this.userlockingid = userlockingid;
    }
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public Date getLockDate() {
        return this.lockDate;
    }
    
    public void setLockDate(Date lockDate) {
        this.lockDate = lockDate;
    }
    public String getLockReason() {
        return this.lockReason;
    }
    
    public void setLockReason(String lockReason) {
        this.lockReason = lockReason;
    }
    public Date getUnlockDate() {
        return this.unlockDate;
    }
    
    public void setUnlockDate(Date unlockDate) {
        this.unlockDate = unlockDate;
    }
    public char getOpcode() {
        return this.opcode;
    }
    
    public void setOpcode(char opcode) {
        this.opcode = opcode;
    }
    public Integer getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(Integer modifiedby) {
        this.modifiedby = modifiedby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }




}


